title: Verkilo
email: merovex@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# collections:
#   - faqs
#   - updates
#   - docs

collections:
  faqs:
    # permalink: /faq/:name
    output: true
  updates:
    permalink: /updates/:name
    output: true
  docs:
    permalink: /docs/:name
    output: true
    order:
      - overview.md
      - setup.md
      - trimsize.md
      - font.md
      - bibliography.md

defaults:
  - scope:
      path: ""
      type: "updates"
    values:
      layout: "update"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
